// Code generated by github.com/gobuffalo/mapgen. DO NOT EDIT.

package cobra

import (
	"sort"
	"sync"
)

// plugMap wraps sync.Map and uses the following types:
// key:   string
// value: plug
type plugMap struct {
	data *sync.Map
	init sync.Once
}

func (m *plugMap) Data() *sync.Map {
	m.init.Do(func() {
		if m.data == nil {
			m.data = &sync.Map{}
		}
	})
	return m.data
}

// Delete the key from the map
func (m *plugMap) Delete(key string) {
	m.Data().Delete(key)
}

// Load the key from the map.
// Returns plug or bool.
// A false return indicates either the key was not found
// or the value is not of type plug
func (m *plugMap) Load(key string) (plug, bool) {
	i, ok := m.Data().Load(key)
	if !ok {
		return plug{}, false
	}
	s, ok := i.(plug)
	return s, ok
}

// LoadOrStore will return an existing key or
// store the value if not already in the map
func (m *plugMap) LoadOrStore(key string, value plug) (plug, bool) {
	i, _ := m.Data().LoadOrStore(key, value)
	s, ok := i.(plug)
	return s, ok
}

// LoadOr will return an existing key or
// run the function and store the results
func (m *plugMap) LoadOr(key string, fn func(*plugMap) (plug, bool)) (plug, bool) {
	i, ok := m.Load(key)
	if ok {
		return i, ok
	}
	i, ok = fn(m)
	if ok {
		m.Store(key, i)
		return i, ok
	}
	return i, false
}

// Range over the plug values in the map
func (m *plugMap) Range(f func(key string, value plug) bool) {
	m.Data().Range(func(k, v interface{}) bool {
		key, ok := k.(string)
		if !ok {
			return false
		}
		value, ok := v.(plug)
		if !ok {
			return false
		}
		return f(key, value)
	})
}

// Store a plug in the map
func (m *plugMap) Store(key string, value plug) {
	m.Data().Store(key, value)
}

// Keys returns a list of keys in the map
func (m *plugMap) Keys() []string {
	var keys []string
	m.Range(func(key string, value plug) bool {
		keys = append(keys, key)
		return true
	})
	sort.Strings(keys)
	return keys
}
